#!/bin/sh
# Used in PaiBloxx by Paisseon

echo() {
	printf %s\\n "$*"
}

if test $(/usr/bin/id -u) -ne 0; then
	echo "Anta baka?! Didn't you read the depiction? Run me as root next time, dummy."
	exit
fi

if test "$1" = "-e"; then
	echo "Enabling ad-block..."
	plutil -Proxies -ProxyAutoConfigEnable -int 1 '/var/mobile/Media/com.apple.SystemConfiguration.plist'
elif test "$1" = "-d"; then
	echo "Disabling ad-block..."
	plutil -Proxies -ProxyAutoConfigEnable -int 0 '/var/mobile/Media/com.apple.SystemConfiguration.plist'
elif test "$1" = "-m"; then
	echo "Switching PAC to MyBloxx..."
	plutil -Proxies -ProxyAutoConfigURLString -string 'https://archive.org/download/MYbloXXforiOS/MYbloXX.pac' '/var/mobile/Media/com.apple.SystemConfiguration.plist'
elif test "$1" = "-p"; then
	echo "Switching PAC to PaiBloxx..."
	plutil -Proxies -ProxyAutoConfigURLString -string 'https://raw.githubusercontent.com/Paisseon/PaiBloxx/emt/proxy.pac' '/var/mobile/Media/com.apple.SystemConfiguration.plist'
else
	echo "Invalid argument supplied, doing nothing."
	exit
fi

echo "Done!"