#!/bin/sh
# Used in PaiBloxx by Paisseon

echo() {
	printf %s\\n "$*"
}

if test $(/usr/bin/id -u) -ne 0; then
	echo "Anta baka?! Didn't you read the depiction? Run me as root next time, dummy."
	exit
fi

if test "$1" = "-e"; then
	echo "Enabling ad-block..."
	plutil -Proxies -ProxyAutoConfigEnable -int 1 '/var/mobile/Media/com.apple.SystemConfiguration.plist'
elif test "$1" = "-d"; then
	echo "Disabling ad-block..."
	plutil -Proxies -ProxyAutoConfigEnable -int 0 '/var/mobile/Media/com.apple.SystemConfiguration.plist'
elif test "$1" = "-m"; then
	echo "Switching PAC to MyBloxx..."
	plutil -Proxies -ProxyAutoConfigURLString -string 'https://archive.org/download/MYbloXXforiOS/MYbloXX.pac' '/var/mobile/Media/com.apple.SystemConfiguration.plist'
elif test "$1" = "-p"; then
	echo "Switching PAC to PaiBloxx Default..."
	plutil -Proxies -ProxyAutoConfigURLString -string 'https://raw.githubusercontent.com/Paisseon/PaiBloxx/emt/PACs/proxy.pac' '/var/mobile/Media/com.apple.SystemConfiguration.plist'
elif test "$1" = "-x"; then
	echo "Switching PAC to PaiBloxx Experimental..."
	plutil -Proxies -ProxyAutoConfigURLString -string 'https://raw.githubusercontent.com/Paisseon/PaiBloxx/emt/PACs/xp.pac' '/var/mobile/Media/com.apple.SystemConfiguration.plist'
elif test "$1" = "-s"; then
	if test -e '/var/mobile/Media/com.apple.SystemConfiguration.plist'; then
		plistEnabled=$(echo $(plutil -v -Proxies -ProxyAutoConfigEnable /var/mobile/Media/com.apple.SystemConfiguration.plist) | tail -c 2)
		plistPac=$(echo $(plutil -v -Proxies -ProxyAutoConfigURLString /var/mobile/Media/com.apple.SystemConfiguration.plist) | tail -c 7)
	fi
	
	if test -e '/var/mobile/Media/com.apple.SystemConfiguration.bak'; then
		echo "PaiBloxx Status: $(tput setaf 1)Disabled$(tput sgr0)"
		exit
	elif test "$plistEnabled" = "0"; then
		echo "PaiBloxx Status: $(tput setaf 1)Disabled$(tput sgr0)"
		exit
	else
		echo "PaiBloxx Status: $(tput setaf 2)Enabled$(tput sgr0)"
	fi
	
	if test "$plistPac" = "XX.pac"; then
		echo "Current PAC: MyBloxx"
	elif test "$plistPac" = "xy.pac"; then
		echo "Current PAC: PaiBloxx Default"
	elif test "$plistPac" = "xp.pac"; then
		echo "Current PAC: PaiBloxx Experimental"
	else
		echo "Current PAC: Unknown"
	fi
	
else
	echo "Invalid argument supplied, doing nothing."
	exit
fi

echo "Done!"