#!/bin/sh
# Used in PaiBloxx by Paisseon

echo() {
	printf %s\\n "$*"
}

if test $(/usr/bin/id -u) -ne 0; then
	echo "Anta baka?! Didn't you read the depiction? Run me as root next time, dummy."
	exit
fi

echo "Switching PAC to MyBloxx..."
plutil -Proxies -ProxyAutoConfigURLString -string 'https://raw.githubusercontent.com/Paisseon/PaiBloxx/emt/proxy.pac' '/var/mobile/Media/com.apple.SystemConfiguration.plist'

echo "Done!"

cfnReload